### ISSUE TITLE
pivot gauge example crash

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#35]
```
DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/grid/default-Functionalities.html Array[0]
/demo-syncfusion/jspm_packages/npm/bluebird@3.3.4/js/browser/bluebird.min.js:31 Unhandled rejection TypeError: Cannot read property 'nextSibling' of null
    at e.View.e.removeNodes (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:5:28900)
    at http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:1661
    at Array.forEach (native)
    at e.ViewSlot.e.removeAll (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:1517)
    at t.e.Repeat.t.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:20:19503)
    at e.Controller.e.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:18401)
    at e.View.e.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:5:28487)
    at e.If.e.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:20:824)
    at e.Controller.e.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:18401)
    at e.View.e.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:5:28487)
    at e.Controller.e.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:18348)
    at e.View.e.unbind (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:5:28487)
    at e.ViewFactory.e.returnViewToCache (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:5226)
    at e.View.e.returnToCache (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:5:27305)
    at a (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:1768)
    at e.ViewSlot.e.removeAll (http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/app-build-67f22cc274.js:6:1866)
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/circulargauge/basic-use.html Array[0]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/circulargauge/half-circular.html Array[0]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/circulargauge/pointer-image.html Array[0]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/circulargauge/unit-label.html Array[0]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/circulargauge/user-interaction.html Array[0]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/spreadsheet/default-functionalities.html Array[1]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/spreadsheet/import-export.html Array[1]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/spreadsheet/chart.html Array[1]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/spreadsheet/pivot.html Array[1]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/spreadsheet/movie-list.html Array[1]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/pivotgauge/basic-use.html Array[1]
/demo-syncfusion/src/app-build-67f22cc274.js:19 DEBUG [templating] importing resources for http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/pivotgauge/OLAP.html Array[1]
ej.spreadsheet.min.js:10 Uncaught TypeError: Cannot read property 'activeSheetIndex' of nullgetActiveSheetIndex @ ej.spreadsheet.min.js:10_refreshSheetonResize @ ej.spreadsheet.min.js:10(anonymous function) @ ej.spreadsheet.min.js:10
```

**Comment by karthickthangasamy** [comment]
This issue has been resolved. [demo](http://aurelia-ui-toolkits.github.io/demo-syncfusion/#/samples/pivotgauge/OLAP)
