### ISSUE TITLE
Kanban current does not render in the bridge demo application

### ISSUE THREAD

**Issue by scotru** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#42]
The Kanban demo at: http://aurelia-ui-toolkits.github.io/demo-syncfusion/#/samples/kanban/default does not currently render but fails with:

http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/kanban/KanbanJsonData.js Failed to load resource: the server responded with a status of 404 (Not Found)
bluebird.min.js:31 Unhandled rejection Error: XHR error (404 Not Found) loading http://aurelia-ui-toolkits.github.io/demo-syncfusion/src/samples/kanban/KanbanJsonData.js
    at o (http://aurelia-ui-toolkits.github.io/demo-syncfusion/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.I.s.onreadystatechange (http://aurelia-ui-toolkits.github.io/demo-syncfusion/jspm_packages/system.js:4:13219)

Missing data file?

**Comment by scotru** [comment]
Sorry--posted in wrong repo.  Will repost in demo-syncfusion
