### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by stuartbloom** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#53]
Hi experts I am hoping someone can help and I am sorry if this is a silly issue.  I have followed the jspm installation instructions as per the Aurelia-Syncfusion bridge installtion page.

I had an error running `jspm install npm:aurelia-syncfusion-bridge css`, stating:

```
warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up npm:aurelia-syncfusion-bridge
     Updating registry cache...

warn Error on lookup for npm:aurelia-syncfusion-bridge, retrying (1).
     Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443

warn Error on locate for jspm:css, retrying (1).
     Error: Command failed: git fetch --all && git reset --hard origin/master
     fatal: unable to access 'https://github.com/jspm/registry.git/': Couldn't resolve host 'github.com'
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:206:12)
         at emitTwo (events.js:106:13)
         at ChildProcess.emit (events.js:191:7)
         at maybeClose (internal/child_process.js:877:16)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

warn Error on locate for jspm:css, retrying (2).
     Error: Command failed: git fetch --all && git reset --hard origin/master
     fatal: unable to access 'https://github.com/jspm/registry.git/': Couldn't resolve host 'github.com'
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:206:12)
         at emitTwo (events.js:106:13)
         at ChildProcess.emit (events.js:191:7)
         at maybeClose (internal/child_process.js:877:16)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

arn Error on locate for jspm:css, retrying (3).
     Error: Command failed: git fetch --all && git reset --hard origin/master
     fatal: unable to access 'https://github.com/jspm/registry.git/': Couldn't resolve host 'github.com'
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:206:12)
         at emitTwo (events.js:106:13)
         at ChildProcess.emit (events.js:191:7)
         at maybeClose (internal/child_process.js:877:16)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

warn Error on locate for jspm:css
     Error: Command failed: git fetch --all && git reset --hard origin/master
     fatal: unable to access 'https://github.com/jspm/registry.git/': Couldn't resolve host 'github.com'
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:206:12)
         at emitTwo (events.js:106:13)
         at ChildProcess.emit (events.js:191:7)
         at maybeClose (internal/child_process.js:877:16)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

err  Error locating jspm:css.

warn Installation changes not saved.
```

now, when I load the application after adding the plugin into the main.ts I get the following error:
`GET http://localhost:9000/src/aurelia-syncfusion-bridge.js `

I guess this is down to my initial problem.  Can someone point me in the right direction?

In order to assist in diagnosis, I have attached what I hope are the relevant files from my setup.

[files.zip](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/files/859070/files.zip)

Thanks in advance

**Comment by Thanood** [comment]
Well, the first warning appears to advice you to run `npm install --save-dev jspm` to install a local version if jspm. 😃 

The rest of the logs seem to be failing DNS requests because none of the host names used by JSPM can be resolved. Can you ping the hosts used in these requests?

- github.com
- registry.npmjs.org

It looks like a network failure, maybe because of a proxy or firewall not forwarding or blocking these requests.

**Comment by stuartbloom** [comment]
@Thanood thanks for your help.  The installation now seems to work OK, however, wehn I have the plugin setup in main.ts and the require in the app.html I am now getting an error:

`GET http://localhost:9000/src/aurelia-syncfusion-bridge.js `

followed by:

```
Unhandled rejection Error: Script error for "aurelia-syncfusion-bridge"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://localhost:9000/scripts/vendor-bundle.js:3945:17)
    at HTMLScriptElement.onScriptError (http://localhost:9000/scripts/vendor-bundle.js:5515:36)
From previous event:
    at DefaultLoader.loadModule (http://localhost:9000/scripts/vendor-bundle.js:13737:14)
    at _loadPlugin (http://localhost:9000/scripts/vendor-bundle.js:12782:21)
    at http://localhost:9000/scripts/vendor-bundle.js:12775:16
From previous event:
    at loadPlugin (http://localhost:9000/scripts/vendor-bundle.js:12774:75)
    at next (http://localhost:9000/scripts/vendor-bundle.js:13036:20)
From previous event:
    at next (http://localhost:9000/scripts/vendor-bundle.js:13036:56)
    at http://localhost:9000/scripts/vendor-bundle.js:13043:16
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:13028:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:12644:39)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:192:17)
    at http://localhost:9000/scripts/vendor-bundle.js:11543:22
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:11538:48)
    at handleApp (http://localhost:9000/scripts/vendor-bundle.js:11529:12)
    at http://localhost:9000/scripts/vendor-bundle.js:11562:13
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:11560:40
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:11559:29
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:11555:26)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:11582:3)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5473:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:4660:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4953:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5334:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4938:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3911:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3836:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4890:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4565:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5237:36
printWarning @ vendor-bundle.js:1395
formatAndLogError @ vendor-bundle.js:1111
fireRejectionEvent @ vendor-bundle.js:1136
Promise._notifyUnhandledRejection @ vendor-bundle.js:582
(anonymous) @ vendor-bundle.js:132
```

Would you have any pointers?

Thanks again

Stuart

**Comment by JeroenVinke** [comment]
Hey Stuart. I believe you are using the CLI. Instead of the installation instructions on the catalog, try and follow [these instructions](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki/CLI-Integration).

**Comment by stuartbloom** [comment]
Thanks @JeroenVinke that was it :)

Now to fight another fire ;)

**Comment by karthickthangasamy** [comment]
@stuartbloom We followed the aurelia-cli integration [instructions](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/wiki/CLI-Integration) and rendered Syncfusion Aurelia Grid component in the below attached sample.

[aurelia-syncfusion.zip](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/files/861064/aurelia-syncfusion.zip)

Could you please try it out and let us know if you are still facing issues with install and configuration.?

**Comment by stuartbloom** [comment]
sorry @karthickthangasamy yes, all good thanks :)  now working on styling :)

**Comment by karthickthangasamy** [comment]
@stuartbloom  👍
