### ISSUE TITLE
Update 2.2.0 => 15.4.17 broken

### ISSUE THREAD

**Issue by VagyokC4** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#80]
I just updated my project to use the latest 2.2.0 bridge with 15.4.17 JS and now I'm getting the following error:

> Unhandled rejection TypeError: jQuery(...)[this.controlName] is not a function
    at ejDatePicker.createWidget (webpack-internal:///aurelia-syncfusion-bridge/common/widget-base:60:77)
    at ejDatePicker.attached (webpack-internal:///aurelia-syncfusion-bridge/common/widget-base:151:10)
    at ejDatePicker.descriptor.value [as attached] (webpack-internal:///aurelia-syncfusion-bridge/common/decorators:79:13)
    at Controller.attached (webpack-internal:///6:3528:22)
    at View.attached (webpack-internal:///6:1578:22)
    at Controller.attached (webpack-internal:///6:3532:17)
    at View.attached (webpack-internal:///6:1578:22)
    at Controller.attached (webpack-internal:///6:3532:17)
    at View.attached (webpack-internal:///6:1578:22)
    at ViewSlot.attached (webpack-internal:///6:1936:13)
    at View.attached (webpack-internal:///6:1583:19)
    at ViewSlot.attached (webpack-internal:///6:1936:13)
    at eval (webpack-internal:///aurelia-framework:326:28)
From previous event:
    at Aurelia.setRoot (webpack-internal:///aurelia-framework:324:40)
    at Object._callee$ (webpack-internal:///main:374:21)
    at tryCatch (webpack-internal:///522:65:40)
    at Generator.invoke [as _invoke] (webpack-internal:///522:299:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///522:117:21)
    at step (webpack-internal:///main:286:191)
From previous event:
    at step (webpack-internal:///main:286:337)
    at eval (webpack-internal:///main:286:437)
From previous event:
    at Object.eval (webpack-internal:///main:286:99)
    at Object.configure (webpack-internal:///main:397:17)
    at eval (webpack-internal:///1042:129:27)
From previous event:
    at config (webpack-internal:///1042:124:54)
    at eval (webpack-internal:///1042:160:12)
From previous event:
    at bootstrap (webpack-internal:///1042:159:24)
    at eval (webpack-internal:///1042:146:7)
From previous event:
    at run (webpack-internal:///1042:141:59)
    at Object.eval (webpack-internal:///1042:166:16)
    at eval (webpack-internal:///1042:167:30)
    at Object.1042 (http://localhost:9000/app.cb9a0869f527a7e3e6fa.bundle.js:514:1)
    at __webpack_require__ (http://localhost:9000/app.cb9a0869f527a7e3e6fa.bundle.js:50:30)
    at Object.420 (http://localhost:9000/app.cb9a0869f527a7e3e6fa.bundle.js:3056:1)
    at __webpack_require__ (http://localhost:9000/app.cb9a0869f527a7e3e6fa.bundle.js:50:30)
    at http://localhost:9000/app.cb9a0869f527a7e3e6fa.bundle.js:145:18
    at http://localhost:9000/app.cb9a0869f527a7e3e6fa.bundle.js:148:10

I was not getting this error in the previous release.  Any ideas on how to resolve?

**Comment by karthickthangasamy** [comment]
@VagyokC4 We made breaking changes to optimise the bundling process, In which we have to refer the 'syncfusion-javascript' widget in sample to overcome this issue. Refer to the below link for detailed information.

https://help.syncfusion.com/aurelia/release-notes/v15.4.0.17?type=all#common-breaking-changes

Thanks,
Karthick T

**Comment by adriatic** [comment]
@karthickthangasamy @JeroenVinke I am very happy to see that you managed to create this release. 😄

**Comment by VagyokC4** [comment]
@karthickthangasamy That worked!  Thank-you for the prompt response.
