### ISSUE TITLE
15.4.20 broken

### ISSUE THREAD

**Issue by AlainBaslter** [aurelia-ui-toolkits/aurelia-syncfusion-bridge#83]
I have been using this in an app for a while and recently tested the Syncfusion Essentials release 15.4.20 separately before updating my app. Myself and my colleague are having the exact same issue...

bluebird.min.js:31 Unhandled rejection TypeError: jQuery(...)[this.controlName] is not a function
    at ejButton.createWidget (http://localhost:9000/jspm_packages/npm/aurelia-syncfusion-bridge@2.2.1/common/widget-base.js:60:79)
    at ejButton.attached (http://localhost:9000/jspm_packages/npm/aurelia-syncfusion-bridge@2.2.1/common/widget-base.js:151:12)
    at ejButton.descriptor.value [as attached] (http://localhost:9000/jspm_packages/npm/aurelia-syncfusion-bridge@2.2.1/common/decorators.js:68:15)
    at Controller.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:3525:24)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:1575:24)
    at ViewSlot.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:1933:15)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:1580:21)
    at ViewSlot.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.7.0/aurelia-templating.js:1933:15)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-framework@1.1.5/aurelia-framework.js:206:30)
    at r (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:33:7722)
    at i._settlePromiseFromHandler (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13044)
    at i._settlePromise (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13847)
    at i._settlePromise0 (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:14548)
    at i._settlePromises (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:15878)
    at r._drainQueue (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3148)
    at r._drainQueues (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3209)

Our starting point is...

Get Aurelia Skeleton Typescript 
https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript
follow install instructions there...
npm install
jspm install

We also do 

jspm update

To get the latest Aurelia modules (the skeleton has not been updated yet?)

gulp watch and make sure it runs

Then we follow the instructions here using the Installation Instructions. We use the jspm approach.

Then a simple ejButton is added to welcome.html  replacing the existing <button> there...

      <button id="normalBtn" 
        ej-button="e-size.bind: normalBtnValue;
        e-show-rounded-corner.bind: roundedCorner;
        e-content-type: imageonly;
        e-prefix-icon: e-icon e-uiLight e-handup">
      </button>

Then add this to the view model welcome.ts

 // tslint:disable-next-line:no-unused-variable
 private normalBtnValue: string = 'normal';
 // tslint:disable-next-line:no-unused-variable
 private roundedCorner: boolean = true;

That's all. 

We both get the same error on line 60 in widget-base.js

      this.eWidget = this.widget = jQuery($(option.element))[this.controlName](this.allOption).data(this.controlName);

This used to all work ok in our app which is still using 14.4.20

We want to upgrade.

What has gone wrong? How do we fix it?

Thanks

**Comment by karthickthangasamy** [comment]
@AlainBaslter We made breaking changes to optimise the bundling process, In which we have to refer the `syncfusion-javascript` widget in sample to overcome this issue. Refer to the below link for detailed information.

https://help.syncfusion.com/aurelia/release-notes/v15.4.0.17?type=all#common-breaking-changes

Please let us know if you need further assistance on this.

Thanks,
Karthick T

**Comment by AlainBaslter** [comment]
@karthickthangasamy 
Thanks for your quick response as usual.
That takes care of it.
In fact that solves the next problem I started tackling too: Bundling.
This change sure makes it easier to bundle something I had not addressed up until now in my app.

**Comment by karthickthangasamy** [comment]
@AlainBaslter We are happy the issue resolved and thanks for your valuable feedback. 👍
